name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your branch name if it's not 'main'
      - master  # Optional: Add master if you use that branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set the version if you're using Node.js

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # If you're using a build process like React, Vue, etc.

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Replace with your build directory (e.g., dist, public)
